// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Fj3zp6_x0pBHZ3eLNNIQ2cQZfGRwZfQ',
    appId: '1:402256817172:web:a83c8877b86279edf24b01',
    messagingSenderId: '402256817172',
    projectId: 'vitawatch',
    authDomain: 'vitawatch.firebaseapp.com',
    storageBucket: 'vitawatch.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyyyZIs2kGwFeamXu76Yd4KTfhSpO6SBQ',
    appId: '1:402256817172:android:deadd0ef8d224575f24b01',
    messagingSenderId: '402256817172',
    projectId: 'vitawatch',
    storageBucket: 'vitawatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWS1qqPWf-2VV7xZs1WwDUi-Fvc6thNHw',
    appId: '1:402256817172:ios:054bbff3789e16f5f24b01',
    messagingSenderId: '402256817172',
    projectId: 'vitawatch',
    storageBucket: 'vitawatch.firebasestorage.app',
    iosBundleId: 'com.example.se2FinHmeas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWS1qqPWf-2VV7xZs1WwDUi-Fvc6thNHw',
    appId: '1:402256817172:ios:054bbff3789e16f5f24b01',
    messagingSenderId: '402256817172',
    projectId: 'vitawatch',
    storageBucket: 'vitawatch.firebasestorage.app',
    iosBundleId: 'com.example.se2FinHmeas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Fj3zp6_x0pBHZ3eLNNIQ2cQZfGRwZfQ',
    appId: '1:402256817172:web:872b958ab40f8462f24b01',
    messagingSenderId: '402256817172',
    projectId: 'vitawatch',
    authDomain: 'vitawatch.firebaseapp.com',
    storageBucket: 'vitawatch.firebasestorage.app',
  );
}
